"""Add image column to candidate_list

Revision ID: 1373b6940085
Revises: b6f77e990b58
Create Date: 2026-03-09 00:28:06.924446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1373b6940085'
down_revision = 'b6f77e990b58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidate', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'voter', ['voter_id'], ['id'])

    with op.batch_alter_table('candidate_list', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidate_list', schema=None) as batch_op:
        batch_op.drop_column('image')

    with op.batch_alter_table('candidate', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
