"""Add Vote model and update relationships

Revision ID: 9bd591839701
Revises: df16df38e098
Create Date: 2026-03-08 23:20:02.551915

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9bd591839701'
down_revision = 'df16df38e098'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidate', schema=None) as batch_op:
        batch_op.alter_column('candidate_list_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
        batch_op.drop_constraint(batch_op.f('candidate_ibfk_2'), type_='foreignkey')
        batch_op.drop_column('votes')
        batch_op.drop_column('voter_id')

    with op.batch_alter_table('candidate_list', schema=None) as batch_op:
        batch_op.alter_column('election_period_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)

    with op.batch_alter_table('vote', schema=None) as batch_op:
        batch_op.add_column(sa.Column('candidate_list_id', sa.Integer(), nullable=False))
        batch_op.alter_column('voter_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
        batch_op.alter_column('election_period_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
        batch_op.drop_constraint(batch_op.f('vote_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'candidate_list', ['candidate_list_id'], ['id'])
        batch_op.drop_column('photo')
        batch_op.drop_column('candidate_id')
        batch_op.drop_column('location')

    with op.batch_alter_table('voter', schema=None) as batch_op:
        batch_op.drop_column('has_voted')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('voter', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_voted', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))

    with op.batch_alter_table('vote', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', mysql.VARCHAR(length=256), nullable=True))
        batch_op.add_column(sa.Column('candidate_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('photo', mysql.VARCHAR(length=256), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('vote_ibfk_1'), 'candidate', ['candidate_id'], ['id'])
        batch_op.alter_column('election_period_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('voter_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.drop_column('candidate_list_id')

    with op.batch_alter_table('candidate_list', schema=None) as batch_op:
        batch_op.alter_column('election_period_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)

    with op.batch_alter_table('candidate', schema=None) as batch_op:
        batch_op.add_column(sa.Column('voter_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('votes', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('candidate_ibfk_2'), 'voter', ['voter_id'], ['id'])
        batch_op.alter_column('candidate_list_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)

    # ### end Alembic commands ###
