"""Initial migration.

Revision ID: b6f77e990b58
Revises: 9bd591839701
Create Date: 2026-03-09 00:01:50.450228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6f77e990b58'
down_revision = '9bd591839701'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidate', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('voter_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'voter', ['voter_id'], ['id'])

    with op.batch_alter_table('candidate_list', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidate_list', schema=None) as batch_op:
        batch_op.drop_column('image')

    with op.batch_alter_table('candidate', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('voter_id')
        batch_op.drop_column('image')

    # ### end Alembic commands ###
