"""Add names to Voter and link them to periods

Revision ID: df16df38e098
Revises: a48a4c401264
Create Date: 2026-03-08 21:18:54.401596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df16df38e098'
down_revision = 'a48a4c401264'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('voter_period_association',
    sa.Column('voter_id', sa.Integer(), nullable=True),
    sa.Column('election_period_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['election_period_id'], ['election_period.id'], ),
    sa.ForeignKeyConstraint(['voter_id'], ['voter.id'], )
    )
    with op.batch_alter_table('candidate', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dignity', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('voter_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'voter', ['voter_id'], ['id'])

    with op.batch_alter_table('voter', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('lastname', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('voter', schema=None) as batch_op:
        batch_op.drop_column('lastname')
        batch_op.drop_column('name')

    with op.batch_alter_table('candidate', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('voter_id')
        batch_op.drop_column('dignity')

    op.drop_table('voter_period_association')
    # ### end Alembic commands ###
